name: Terraform CI/CD

on:
  push:
    branches: [main]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5

      # 3. Configure AWS credentials from secrets
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 4. Test AWS connection
      - name: Test AWS Connection
        run: aws sts get-caller-identity

      # 5. Terraform Init
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      # 6. Terraform Plan
      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform
